version: "3.7"

services:
  arbot:
    image: comdotwww/arbot
    network_mode: host
    restart: always
    container_name: arbot
    volumes:
      #aria2下载目录，默认 两个需要保持一致
      - /root/downloads:/root/downloads
      #挂载自定义的目录 方便发送 telgram 后删除文件，不设置，容器会找不到目录
      - /测试:/测试
    environment:
      TZ: Asia/Shanghai
      API_ID: 11111
      API_HASH: 11111
      BOT_TOKEN: 11111:11111
      JSON_RPC_URL: http://11111:6800/jsonrpc  # 目前只支持http，暂不支持SSL
      JSON_RPC_TOKEN: 11111
      SEND_ID: 11111  # bot 主人的id
      #      PROXY_IP:   #可选  代理ip
      #      PROXY_PORT:  #可选 代理端口
      UP_TELEGRAM: 'False' #下载完成后是否上传到Telegram
      IS_DELETED_AFTER_UPLOAD: 'False' # 上传Telegram完成后，是否删除该文件
